### PR TITLE
Rails 6 compatibility

### PR DESCRIPTION
**Pull request by otlaitil**
Support Rails 6 by making runtime dependencies more lax.

### CODE REVIEW

**Comment by alexhanh** [comment]
Thx, @otlaitil! :+1:

**Comment by otlaitil** [comment]
Could you also make a new release to rubygems? :shipit: Thanks a lot @alexhanh!

**Comment by alexhanh** [comment]
Ping @nialhama

**Comment by nialhama** [comment]
1.0.4 has been released to rubygems @alexhanh @otlaitil

**Comment by otlaitil** [comment]
Awesome, thanks @nialhama :raised_hands:

**Pull request merged**
